### ISSUE TITLE
define bounding box for text

### ISSUE THREAD

**Issue by rezakarbasi** [masoudrahimi39/ECG-code#11]
we must make bounding boxes for the lead names which makes is necessary for adaptive lead detection
❗️We may define a label for each of them in the detection network

**Comment by masoudrahimi39** [comment]
bounding box for lead name can be integrated with the code in which bounding boxe for lead is generated. Class number for lead is 0 and class number for lead name is 1.
So, it may achieved by an edition in determine_bb function in utils..py

**Comment by masoudrahimi39** [comment]
is it fine to have bounding boxes with bigger margine?
![3](https://github.com/masoudrahimi39/ECG-code/assets/65596290/c8d45e14-8421-41cb-ba43-6710ae373495)
![2](https://github.com/masoudrahimi39/ECG-code/assets/65596290/ec70db26-588f-4c52-98a2-ddd045649b7c)
![0](https://github.com/masoudrahimi39/ECG-code/assets/65596290/f34582f2-44f4-4bdb-b499-4bc537a5d624)

**Comment by rezakarbasi** [comment]
I think it wouldn't be good for the training process. But I think we can forget about it for now. 
Maybe we'll return to the issue again later.

**Comment by rezakarbasi** [comment]
the problem has been addressed in the last mentioned commit
![2](https://github.com/masoudrahimi39/ECG-code/assets/8475952/17d04de2-17b2-4d94-a51f-8d89a1ba787e)
