### ISSUE TITLE
In plot_v3 function in prepare_image_dataset/adjusted_library/ecg_plot_v2, the origin should be the lower left. 

### ISSUE THREAD

**Issue by masoudrahimi39** [masoudrahimi39/ECG-code#18]
The order of plotting the leads should be from down to up so when a lead is plotted the origin should not be changed because we saved the relative coordinates of the box around the text relative to the origin of the lead.

**Comment by rezakarbasi** [comment]
The issue has been addressed due to the mentioned commit
![2](https://github.com/masoudrahimi39/ECG-code/assets/8475952/9749aff0-64a7-493a-b77d-d18cc7b40018)
