### ISSUE TITLE
negative label, i.e. (x, y) of bounding box

### ISSUE THREAD

**Issue by masoudrahimi39** [masoudrahimi39/ECG-code#22]
Ultralytics ignore data points whose lables (x and y of bounding box) are negative. 
Also, I think labels should be normalized and fall within [0, 1] according to [`this issue from Ultralytics`](https://github.com/ultralytics/ultralytics/issues/707)

---
This is the warning I get in training process: 

![image](https://github.com/masoudrahimi39/ECG-code/assets/65596290/16f2018c-4a89-4cb0-8539-8cd2250b759c)

**Comment by rezakarbasi** [comment]
Have you generated the dataset again? 
I haven't faced such problem

**Comment by masoudrahimi39** [comment]
Yes, I generated 800 samples.

**Comment by rezakarbasi** [comment]
the problematic samples do not contain any negative values now
Please check it out

**Comment by masoudrahimi39** [comment]
I have tested the model and encounter this issue. Please test the model with 1000 samples.

**Comment by masoudrahimi39** [comment]
This is the a label containing negative values.
[328_3by4.txt](https://github.com/masoudrahimi39/ECG-code/files/15360186/328_3by4.txt)
