### ISSUE TITLE
please check draw_bb function

### ISSUE THREAD

**Issue by masoudrahimi39** [masoudrahimi39/ECG-code#25]
When it loads an image, it removes the lower and left parts of the image and plot the boding box. The bounding boxes seem correct in this way. Yet, in our original dataset_v4, still we have the borders and I think labels are not correct. Please check it.

**Comment by masoudrahimi39** [comment]
file_path = sample['save_path']
    I mean  `img = img[:-34, 34:, :]` in the below piece of code:
    
    
    `img = plt.imread(file_path)
    img = img[:-34, 34:, :]
    img_size = img.shape
    img_width = img_size[1]
    img_height = img_size[0]`

**Comment by rezakarbasi** [comment]
resolved with the abovementioned commit
